export const FOCUS_PRESETS = {
  steady: {
    id: 'steady',
    label: 'Steady',
    beatHz: 6,
    leftHz: 220,
    rightHz: 226,
    noiseType: 'pink',
    noiseVolume: 0.08,
    filterRange: [860, 2100],
    beatDrift: 0.45,
    description: 'Balanced focus with a calm pulse, gentle lift, and warm sustained motion.',
    progression: [
      { chord: ['D3', 'A3', 'F#4'], shimmer: ['E4'], duration: 24, velocity: 0.34 },
      { chord: ['B2', 'F#3', 'D4'], shimmer: ['F#4'], duration: 22, velocity: 0.4 },
      { chord: ['G3', 'D4', 'B4'], shimmer: ['A4'], duration: 24, velocity: 0.46 },
      { chord: ['E3', 'B3', 'G4'], shimmer: ['B4'], duration: 21, velocity: 0.5 },
      { chord: ['A3', 'E4', 'B4'], shimmer: ['B4'], duration: 22, velocity: 0.56 },
      { chord: ['D3', 'A3', 'F#4', 'E5'], shimmer: ['A4'], duration: 30, velocity: 0.62 },
    ],
  },
  deep: {
    id: 'deep',
    label: 'Deep',
    beatHz: 4,
    leftHz: 196,
    rightHz: 200,
    noiseType: 'brown',
    noiseVolume: 0.06,
    filterRange: [620, 1580],
    beatDrift: 0.85,
    description: 'Darker and slower, with grounded weight, soft width, and deeper release.',
    progression: [
      { chord: ['D3', 'A3', 'F4'], shimmer: ['A4'], duration: 26, velocity: 0.28 },
      { chord: ['F3', 'C4', 'A4'], shimmer: ['G4'], duration: 24, velocity: 0.34 },
      { chord: ['G3', 'D4', 'A4'], shimmer: ['A4'], duration: 24, velocity: 0.4 },
      { chord: ['A3', 'E4', 'C5'], shimmer: ['E4'], duration: 22, velocity: 0.46 },
      { chord: ['Bb3', 'F4', 'D5'], shimmer: ['F4'], duration: 22, velocity: 0.52 },
      { chord: ['D3', 'A3', 'F4', 'E5'], shimmer: ['A4'], duration: 32, velocity: 0.58 },
    ],
  },
  driftless: {
    id: 'driftless',
    label: 'Drift Less',
    beatHz: 8,
    leftHz: 248,
    rightHz: 256,
    noiseType: 'pink',
    noiseVolume: 0.1,
    filterRange: [980, 2440],
    beatDrift: 0.3,
    description: 'A little brighter and more alert, but still smooth, stable, and immersive.',
    progression: [
      { chord: ['C3', 'G3', 'D4'], shimmer: ['D4'], duration: 22, velocity: 0.34 },
      { chord: ['A2', 'E3', 'C4'], shimmer: ['E4'], duration: 22, velocity: 0.38 },
      { chord: ['F3', 'C4', 'A4'], shimmer: ['G4'], duration: 20, velocity: 0.42 },
      { chord: ['G3', 'D4', 'A4'], shimmer: ['A4'], duration: 20, velocity: 0.46 },
      { chord: ['D3', 'A3', 'F4'], shimmer: ['A4'], duration: 22, velocity: 0.5 },
      { chord: ['C3', 'G3', 'E4', 'D5'], shimmer: ['G4'], duration: 30, velocity: 0.56 },
    ],
  },
}

export const FOCUS_EFFECTS = [
  { id: 'rain', label: 'Rain' },
  { id: 'rainTarp', label: 'Rain Tarp' },
  { id: 'birds', label: 'Birds' },
  { id: 'wind', label: 'Wind' },
  { id: 'thunder', label: 'Thunder' },
  { id: 'seaside', label: 'Seaside' },
  { id: 'fireplace', label: 'Fireplace' },
]
